name: "CI"

on:
  pull_request:

jobs:
  ci:
    name: Build examples and run tests
    runs-on: ubuntu-24.04
    env:
      REACTOR_UC_PATH: ${{ github.workspace }}/reactor-uc

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone reactor-uc runtime
        run: git clone https://github.com/lf-lang/reactor-uc.git --recursive -b ci-zephyr-template

      - name: Install LFC dependencies
        uses: ./reactor-uc/.github/actions/lingua-franca
      
      - name: Install Zephyr dependencies
        uses: ./reactor-uc/.github/actions/zephyr
        with:
          clone-template: false


      - name: Pull down Zephyr RTOS
        run: |
          west update
          west zephyr-export
          pip install -r deps/zephyr/scripts/requirements.txt
          echo "ZEPHYR_BASE=${{github.workspace}}/deps/zephyr" >> $GITHUB_ENV

      - name: Run tests
        run: ./.github/scripts/run-all.sh